### PR TITLE
Makefile update to include yarn command

### PR DESCRIPTION
**Pull request by Nyzl**
make start will now also run yarn

### CODE REVIEW

**Comment by ChrisBrettCA** [comment]
@Nyzl Didn't we want to look to detach the `attaching` command from the `restart` command?

**Comment by Nyzl** [comment]
yes, but i've not got round to that yet, this change at least gets yarn ran at start up, where as the rest of the changes are kinda file structure changes with no impact the end user

**Comment by Nyzl** [comment]
happy to wait til it's all ready though

**Comment by ChrisBrettCA** [comment]
@Nyzl I see, my mistake, this PR title does describe that. Let's continue.

**Pull request merged**
