### PR TITLE
Use docker-compose and shared-services

### PR DESCRIPTION
**Pull request by maddiefletcher**
This PR will standardise on the way we use docker for casebook as well as for future projects.

### CODE REVIEW

**Comment by ChrisBrettCA** [comment]
@markpfletcher I'm having some problems getting this set up on my machine. I follow the documentation and everything seems to install correctly. When I run the `reset` command and navigate to the URL documented, I'm getting the documentation site, but I'm not seeing any of the CSS despite it being correctly pulled in and available in the sources panel with no errors being displayed.

**Comment by ChrisBrettCA** [comment]
@markpfletcher I'm thinking of getting the "sandbox" portion of this repo removed as it's unnecessary really. It's easy enough to have a small single/multi page setup working on ones workstation without having all the added extra Jekyll-ness just for a simple playground area and prototyping. Personally I'd rather there was a separation of concerns. I will remove this from the codebase once we have merged in this branch, please could you remove any integration with the branch you created? Thanks.

**Comment by markpfletcher** [comment]
@ChrisBrettCA I've removed the sandbox - can you test this out again?

**Comment by btomy** [comment]
@markpfletcher 
I have managed to get docker working successfully. But wasn't sure how to test the `Shared services` properly. It would be really beneficial if you could spent 5 - 10 mins just going through it please.

**Pull request closed without merging**
