### PR TITLE
Addition of flex classes

### LINKED ISSUE #64: Incorporate `flex-box` into the grid-system

### PR DESCRIPTION
**Pull request by adam-parsons-ca**
Resolves #64 Incorporate `flex-box` into the grid-system

### CODE REVIEW

**Comment by adam-parsons-ca** [comment]
@ChrisBrettCA and @btomy. Let me know what you think of this. Class names may need to be shortened somehow.

**Comment by btomy** [comment]
I am not too sure about the class names, might be work shortening them ?

**Comment by ChrisBrettCA** [comment]
This PR requires further thought around the use cases of `flex-box` and whether we need to abstract to classes or not. Perhaps Mixing this into a `layout` component might help here. We need to do some further digging, so will park this PR for the time being.

**Comment by adam-parsons-ca** [comment]
This PR was replaced by #134

**Pull request closed without merging**
